# Generated by Django 4.2.21 on 2025-05-31 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TEC', 'Technician'), ('ADM', 'Administrator'), ('RES', 'Resident'), ('INT', 'Intern')], max_length=3)),
                ('department', models.CharField(max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('shift_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('days_off', models.TextField(blank=True, null=True)),
                ('work_unit', models.CharField(blank=True, choices=[('ICU', 'Intensive Care Unit'), ('ER', 'Emergency Room'), ('CCU', 'Cardiac Care Unit'), ('NICU', 'Neonatal Intensive Care Unit'), ('PACU', 'Post-Anesthesia Care Unit'), ('MED-SURG', 'Medical-Surgical Unit'), ('L&D', 'Labor and Delivery')], max_length=10, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('days_off', models.TextField(blank=True, null=True)),
                ('work_unit', models.CharField(blank=True, choices=[('ICU', 'Intensive Care Unit'), ('ER', 'Emergency Room'), ('CCU', 'Cardiac Care Unit'), ('NICU', 'Neonatal Intensive Care Unit'), ('PACU', 'Post-Anesthesia Care Unit'), ('MED-SURG', 'Medical-Surgical Unit'), ('L&D', 'Labor and Delivery')], max_length=10, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
