"""
Django settings for Emergencies project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*a%b8ku=m5cfu8^wiww)5!t&udt(171s28x926f1q%myqcbfms'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'UI',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'UI.middleware.StaffAccessControlMiddleware',
]

ROOT_URLCONF = 'Emergencies.urls'

WSGI_APPLICATION = 'Emergencies.wsgi.application'

# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP host
# EMAIL_HOST_USER = "your_id@gmail.com"  # Your email address
# EMAIL_HOST_PASSWORD = "your host password"  # Your email password
# EMAIL_PORT = 465  # SMTP port
# EMAIL_USE_SSL = True  # Use SSL for secure connection

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import os

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'UI/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Emergencies.context_processor.get_dashboard_infographics_data',
            ],
        },
    }
]

JAZZMIN_SETTINGS = {
    "show_ui_builder": True,
    "site_title": "Emergencies",
    "site_header": "Emergencies",
    "site_brand": "Emergencies",
    "site_logo": "logo/logo.png",
    "copyright": "Emergencies",
    "custom_css": "css/jazzmin_custom.css",
    "welcome_sign": "Welcome to Emergencies Dashboard",

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",

        "core.patient": "fas fa-user-injured",
        "core.emergencyvisit": "fas fa-truck-medical",
        "core.vitalsign": "fas fa-heart-pulse",
        "core.treatment": "fas fa-syringe",
        "core.diagnosis": "fas fa-file-medical",
        "core.bed": "fas fa-bed",
        "core.admission": "fas fa-procedures",
        "core.staff": "fas fa-user-md",
        "core.inventoryitem": "fas fa-pills",
        "core.prescription": "fas fa-prescription-bottle-alt",
        "core.doctor": "fas fa-user-md",
        "core.nurse": "fas fa-user-nurse",  
    },

    "custom_menu": "Emergencies.context_processor.get_jazzmin_custom_menu",
}