# Generated by Django 4.2.21 on 2025-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MED', 'Medication'), ('EQUIP', 'Equipment'), ('SUPP', 'Medical Supplies'), ('OTHER', 'Other')], max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('minimum_stock', models.PositiveIntegerField()),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
